#make file - this is a comment section

all: driver1 driver2 
	
driver1: driver1.c
	gcc -o driver1 myio.c driver1.c

driver2: driver2.c
	gcc -o driver2 myio.c driver2.c
	
clean:
	rm -f driver1.o driver2.o driver1 driver2
	